### PR TITLE
Fix Travis build for s390x

### PR DESCRIPTION
**Pull request by Prashant-Jagtap**
This PR fixes the CI failures on Travis for s390x.

### CODE REVIEW

**Comment by Prashant-Jagtap** [comment]
@lawrinn could you please have a look?

**Comment by Prashant-Jagtap** [comment]
Hi @lawrinn, could you please have a look at these changes ?

**Comment by Prashant-Jagtap** [comment]
Hi @lawrinn, do you have any update on this ?

**Comment by lawrinn** [comment]
Sorry, I've missed it. I'll take the look

**Comment by lawrinn** [comment]
Done - thank you!

**Comment by Prashant-Jagtap** [comment]
Thank you @lawrinn

**Pull request merged**
